import {
    FaAngleUp,
    FaAt,
    FaBriefcase,
    FaCalendarDays,
    FaCalendarPlus,
    FaCheck,
    FaCircleCheck,
    FaCircleInfo,
    FaDownload,
    FaGithub,
    FaFolderPlus,
    FaLayerGroup,
    FaLinkedin,
    FaLocationDot,
    FaMagnifyingGlass,
    FaMoon,
    FaPencil,
    FaPhone,
    FaRegSun,
    FaStar,
    FaTelegram,
    FaTrashCan,
    FaTriangleExclamation,
    FaUpRightFromSquare,
    FaUsersSlash,
    FaWhatsapp,
    FaXTwitter,
    FaXmark,
} from "react-icons/fa6";

export const Icons = {
    AddExperience: FaCalendarPlus,
    AddProject: FaFolderPlus,
    Calendar: FaCalendarDays,
    Check: FaCheck,
    Download: FaDownload,
    Edit: FaPencil,
    Email: FaAt,
    Experience: FaBriefcase,
    Github: FaGithub,
    Info: FaCircleInfo,
    Linkedin: FaLinkedin,
    Location: FaLocationDot,
    Moon: FaMoon,
    Phone: FaPhone,
    Premium: FaStar,
    Projects: FaLayerGroup,
    Search: FaMagnifyingGlass,
    Sun: FaRegSun,
    Telegram: FaTelegram,
    Trash: FaTrashCan,
    Twitter: FaXTwitter,
    Up: FaAngleUp,
    UserNotFound: FaUsersSlash,
    Warning: FaTriangleExclamation,
    Website: FaUpRightFromSquare,
    Whatsapp: FaWhatsapp,
    Verified: FaCircleCheck,
    X: FaXmark,
};
